---
title: "filtered"
author: "Cian Hughes"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(ggsoccer)

```

```{r}
# Read the "actions" CSV file
actions <- read.csv("data/actions.csv")

```


```{r}
# Function to filter data for specific team IDs
filter_data_for_teams <- function(actions, target_team_ids) {
  game_ids_with_teams <- unique(actions$game_id[actions$team_id %in% target_team_ids])
  
  filtered_data <- actions[actions$game_id %in% game_ids_with_teams, ]
  
  return(filtered_data)
}

desired_team_ids <- c(0000)
# Add your desired team IDs here

filtered_data <- filter_data_for_teams(actions, desired_team_ids)

# Write the filtered data to a new CSV file called "FILTERED.csv"
write.csv(filtered_data, file = "data/filtered.csv", row.names = FALSE)

# Print the total number of unique match IDs
total_unique_match_ids <- length(unique(filtered_data$game_id))
cat("Total number of unique match IDs:", total_unique_match_ids, "\n")
unique(filtered_data$game_id)
```

